# Generated by Django 3.0.5 on 2020-05-02 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_type', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_name', models.CharField(max_length=220)),
                ('uploads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.Uploads')),
            ],
        ),
    ]
