# Generated by Django 3.0.5 on 2020-05-02 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_video_date_uploaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddVid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_type', models.CharField(max_length=220)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='uploads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.AddVid'),
        ),
        migrations.DeleteModel(
            name='Uploads',
        ),
    ]
