# Generated by Django 3.0.5 on 2020-05-02 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20200502_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='uploads',
            new_name='upload',
        ),
    ]
