# Generated by Django 3.0.5 on 2020-05-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_auto_20200502_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='upload',
            new_name='video_type',
        ),
    ]
